version: 1
labels:
  - label: "ci/cd"
    files:
      - ".github/.*"
      - ".github/workflows/.*"
  - label: "branding"
    files:
      - ".*.jpg"
      - ".*.png"
      - ".*.svg"
      - ".*.jpeg"
      - ".*.guf"
      - ".*.css"
  - label: "documentation"
    files:
      - "DisCatSharp.Docs/.*"
  - label: "experimental"
    title: ^[Exp]:.*
  - label: "dependencies"
    files:
      - ".*.csproj"
      - ".*.sln"
