name: "Test Documentation"
on:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build documentation
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token:  ${{ secrets.NYUW_TOKEN_GH }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.x
    - name: Git fetch unshallow
      run: git fetch --unshallow
    - name: Restore packages
      run: dotnet restore
    - name: Build library
      run: dotnet build -c Release
      continue-on-error: true
    - name: Build Docs
      shell: pwsh
      run: ./rebuild-docs.ps1 -DocsPath "./DisCatSharp.Docs" -Output "." -PackageName "dcs-docs"
    - name: Upload packed docs
      uses: actions/upload-artifact@v3
      with:
        name: dcs-docs.zip
        path: dcs-docs.zip
        retention-days: 30
