name: "Release DisCatSharp"

on:
  workflow_dispatch:
    inputs:
      version_suffix:
        description: "Version Suffix"
        required: false
        type: string
      release_as_prerelease:
        description: "Release as pre-release"
        required: true
        type: boolean

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

jobs:
  release:
    timeout-minutes: 30
    runs-on: windows-latest
    name: Build library and release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0.400
      - name: Restore dependencies
        run: dotnet restore
      - name: Build library as full release
        if: ${{!inputs.release_as_prerelease}}
        shell: pwsh
        run: ./rebuild-lib.ps1 -ArtifactLocation ./dcs-artifacts -Configuration Release
      - name: Build library as pre-release
        if: ${{inputs.release_as_prerelease}}
        shell: pwsh
        run: ./rebuild-lib.ps1 -ArtifactLocation ./dcs-artifacts -Configuration Release -VersionSuffix ${{github.event.inputs.version_suffix}}
      - name: Remove invalid packages
        shell: pwsh
        run: rm *.symbols.*
        working-directory: ./dcs-artifacts
      - name: Publish to NuGet
        shell: pwsh
        run: dotnet nuget push --source https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} * --skip-duplicate
        working-directory: ./dcs-artifacts
      - name: Publish to GitHub Packages
        shell: pwsh
        run: dotnet nuget push --source https://nuget.pkg.github.com/Aiko-IT-Systems/index.json -k ${{secrets.GITHUB_TOKEN}} *
        working-directory: ./dcs-artifacts
